version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - TZ:Asia/Seoul
  redis:
    image: redis:alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
